// src/pages/contact.svelte
<main class="contact_page">
        <h1>Contact Us</h1>
        You can reach Daryl and Kristen by phone at (541) 941-9660
        <br />
        by email at daryl@kurlyfries.com
        <br />
        Or by Mail at P.O. Box 188, Cave Junction Oregon, 97523
</main>

<style lang="less">
.contact_page {
    text-align: center;
}
</style>

// client/pages/contact.vue
<template>
    <div class="contact_page">
        <h1>Contact Us</h1>
        You can reach Daryl and Kristen by phone at (541) 941-9660
        <br />
        by email at daryl@kurlyfries.com
        <br />
        Or by Mail at P.O. Box 188, Cave Junction Oregon, 97523
    </div>
</template>

<script>
export default {
    name: 'contact',
}
</script>

<style lang="less">
.contact_page {
    text-align: center;
}
</style>
