// src/pages/home.svelte
<script>
    import headerImg from '../img/new-trailer.jpg'
    
    let lightboxShow = false
    let lightboxImage = ''

    const images = [
        {
            src: '/img/operations/new-trailer.jpg',
            double: true,
            text: [
                'Southern Oregon Food & Beverage is the finest provider of fair food in Southern Oregon and Northern California. With over 30 years of experience, our hard working team provides great food at a great price!',
                'Over the past 30 years we\'ve sold a wide variety of food, from our signature Fresh Giant Kurly Fries, to our famous Hand Dipped Corn Dogs.',
                'From our enormous jumbo burritos, to deep fried candy bars and funnel cakes, we have the flexibility to serve the perfect menu at any event.',
            ],
        },
        {
            src: '/img/operations/sausage-trailer.jpg',
        },
        {
            src: '/img/operations/red_crew.jpg',
        },
        {
            src: '/img/operations/corndog-trailer.jpg',
        },
        {
            src: '/img/operations/yreka.jpg',
        },
        {
            src: '/img/operations/deschutes.jpg',
        },
        {
            src: '/img/operations/kurly-fries.jpg',
        },
        {
            src: '/img/operations/yreka2.jpg',
            double: true,
            text: [
                'With a large arrangement of tents and trailers, we are able to serve at anything from state fairs to small festivals.',
                'If you\'re interested in having us serve at your event you can contact us in a variety of ways from our Contact Page.',
                'We strongly support the industry and are members of Western Fairs Association, Oregon Fair Association, National Independent Concessionaires Association (NICA), and International Association of Fairs and Expositions (IAFE).',
            ],
        },
        {
            src: '/img/operations/50ft.png',
        },
        {
            src: '/img/operations/gus_daryl.jpg',
        },
    ]

    function lightbox(img) {
        console.log(img)
        lightboxImage = img
        lightboxShow = true
    }

    function lightboxHide(e) {
        lightboxShow = false
    }
</script>

<main>
    <div class="headerSection">
        <img src={headerImg} class="headerImage" />
        <h1 class="headerTitle">Southern Oregon Food &amp; Beverage</h1>
    </div>
    
    <section class="homeGallery">
        {#each images as image, imageIndex}
            <div class="galleryItem" class:double={image.double} on:click={() => lightbox(image.src)}>
                <img src={image.src} class="galleryItemImage" />
                {#if image.text}
                <div class="galleryText">
                    {#each image.text as text}
                        <p>{text}</p>
                    {/each}
                </div>
                {/if}
            </div>
        {/each}
    </section>

    <div class="lightbox" class:show={lightboxShow} on:click|stopPropagation={lightboxHide}>
        <div class="lightboxInner">
            <img src={lightboxImage} class="lightboxImage" />
            <div class="closeButton">x</div>
            <a href={lightboxImage} target="__blank" class="fullscreenButton">View Fullscreen >></a>
        </div>
    </div>
</main>

<style lang="less">
.headerSection {
    display: block;
    min-height: 80%;
    position: relative;
    max-height: 90vh;

    .headerImage {
        width: 100%;
        min-height: 80%;
        display: block;
    }

    .headerTitle {
        position: absolute;
        top: 50%;
        transform: translateY(-50%);
        text-align: center;
        color: #fff;
        width: 100%;
        font-size: 5vw;
        text-shadow: 3px 3px 0px #000;
    }
}

.homeGallery {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(25%, 1fr));

    @media screen and (max-width: 1024px) {
        grid-template-columns: repeat(auto-fill, minmax(50%, 1fr));
    }

    @media screen and (max-width: 720px) {
        grid-template-columns: repeat(auto-fill, minmax(100%, 1fr));
    }

    .galleryItem {
        // min-height: 300px;
        width: 100%;
        aspect-ratio: 1;
        position: relative;
        overflow: hidden;
        user-select: none;
        
        &.double {
            grid-column: span 2;
            grid-row: span 2;
        }
        
        &:hover {
            cursor: pointer;
            .galleryItemImage {
                transform: scale(1.1);
             
                @media screen and (max-width: 720px) {
                    transform: none;
                }
            }
        }
        
        .galleryItemImage {
            display: block;
            width: 100%;
            object-fit: cover;
            aspect-ratio: 1;
            transition: transform 0.5s;
        }

        .galleryText {
            position: absolute;
            top: 0px;
            left: 0px;
            width: 100%;
            height: 100%;
            z-index: 100;
            color: #fff;
            background-color: rgba(0, 0, 0, 0.5);
            padding: 10%;
            font-size: 24px;

            @media screen and (max-width: 1024px) {
                font-size: 18px;
            }

            @media screen and (max-width: 720px) {
                padding: 5%;
            }
        }
        
        &:after {
            content: '';
            position: absolute;
            top: 0px;
            left: 0px;
            width: 100%;
            height: 100%;
            z-index: 90;
            box-shadow: inset 0px 0px 10px 0px #000;
        }
    }
}

.lightbox {
    display: none;
    position: fixed;
    width: 100%;
    height: 100%;
    top: 0px;
    left: 0px;
    background-color: rgba(0, 0, 0, 0.5);
    z-index: 500;
    user-select: none;

    &.show {
        display: block;
    }

    .lightboxInner {
        position: absolute;
        width: 90%;
        outline: 10px solid #fff;
        top: 50%;
        left: 50%;
        transform: translateY(-50%) translateX(-50%);

        @media screen and (max-width: 1024px) {
            width: 95%;
            outline-width: 5px;
        }
        
        .lightboxImage {
            width: 100%;
            display: block;
        }
    
        .closeButton {
            position: absolute;
            top: -25px;
            right: -25px;
            background-color: #fff;
            width: 40px;
            height: 40px;
            text-align: center;
            line-height: 35px;
            border-radius: 100px;
            color: #000;
            font-size: 30px;
            cursor: pointer;
            outline: 2px solid #000;

            @media screen and (max-width: 1024px) {
                right: 0px;
                top: -50px;
            }
        }

        .fullscreenButton {
            color: #fff;
            display: block;
            position: absolute;
            right: 10px;
            bottom: 10px;
            font-size: 24px;
            text-shadow: 2px 2px 0px #000;
        }
    }
}
</style>

// client/pages/home.vue
<template>
    <div>
        <h1>Southern Oregon Food &amp; Beverage</h1>
        <p>
            Southern Oregon Food &amp; Beverage is the finest provider of fair food in Southern Oregon and Northern California.
            With over 30 years of experience, our hard working team provides great food at a great price!
        </p>
        <img class="home_trailer_img" src="~img/operations/sausage-trailer.jpg" alt="Our most versatile trailer"/>
        <p>
            Over the past 30 years we've sold a wide variety of food, from our signature Fresh Giant Kurly Fries, to our famous Hand Dipped Corn Dogs.
            From our enormous jumbo burritos, to deep fried candy bars and funnel cakes, we have the flexibility to serve the perfect menu at any event.
        </p>
        <p>
            With a large arrangement of tents and trailers, we are able to serve at anything from state fairs to small festivals.
            If you're interested in having us serve at your event you can contact us in a variety of ways from our Contact Page.
        </p>
        <p>
            We strongly support the industry and are members of Western Fairs Association, Oregon Fair Association, National Independent Concessionaires Association (NICA), and International Association of Fairs and Expositions (IAFE).
        </p>
    </div>
</template>

<script>
export default {
    name: 'home',
}
</script>

<style lang="less">

.home_trailer_img {
    width: 50%;
    margin: 10px;
    float: right;
    border: 2px solid;

    @media screen and (max-width: 600px) {
        display: none;
    }
}
</style>
