// client/pages/affiliates.vue
<template>
    <div class="affiliates_page">
        <h1>Affiliates</h1>

        <div class="affiliate">
            <a href="http://taylorsausage.com" target="_blank" class="affiliate_link">TaylorSausage.com</a>
            <br />
            We are proud to serve Taylor's Gourmet Sausages, a Fair Favorite.
        </div>

        <div class="affiliate">
            <a href="http://www.westernfairs.org/" target="_blank" class="affiliate_link">Western Fairs Association</a>
        </div>

        <div class="affiliate">
            <a href="http://oregonfairs.org/index.php?bypassCookie=1" target="_blank" class="affiliate_link">Oregon Fair Association</a>
        </div>

        <div class="affiliate">
            <a href="http://www.nicainc.org/" target="_blank" class="affiliate_link">National Independent Concessionaires Association (NICA)</a>
        </div>

        <div class="affiliate">
            <a href="https://www.fairsandexpos.com/" target="_blank" class="affiliate_link">International Association of Fairs and Expositions (IAFE)</a>
        </div>
    </div>
</template>

<script>
export default {
    name: 'affiliates',
}
</script>

<style lang="less">
.affiliates_page {
    text-align: center;

    .affiliate {
        margin-bottom: 20px;

        .affiliate_link {
            display: inline-block;
            color: #222;
            padding: 5px 0px;
        }
    }
}
</style>

// src/pages/affiliates.svelte
<main class="affiliates_page">
    <h1>Affiliates</h1>

    <div class="affiliate">
        <a href="http://taylorsausage.com" target="_blank" class="affiliate_link">TaylorSausage.com</a>
        <br />
        We are proud to serve Taylor's Gourmet Sausages, a Fair Favorite.
    </div>

    <div class="affiliate">
        <a href="http://www.westernfairs.org/" target="_blank" class="affiliate_link">Western Fairs Association</a>
    </div>

    <div class="affiliate">
        <a href="http://oregonfairs.org/index.php?bypassCookie=1" target="_blank" class="affiliate_link">Oregon Fair Association</a>
    </div>

    <div class="affiliate">
        <a href="http://www.nicainc.org/" target="_blank" class="affiliate_link">National Independent Concessionaires Association (NICA)</a>
    </div>

    <div class="affiliate">
        <a href="https://www.fairsandexpos.com/" target="_blank" class="affiliate_link">International Association of Fairs and Expositions (IAFE)</a>
    </div>
</main>

<style lang="less">
.affiliates_page {
    text-align: center;

    .affiliate {
        margin-bottom: 20px;

        .affiliate_link {
            display: inline-block;
            color: #222;
            padding: 5px 0px;
        }
    }
}
</style>
