// client/pages/events.vue
<template>
    <div>
        <h1>Our Events</h1>

        <div class="event_list">
    		<a target="_blank" href="http://www.redbluffbullsale.com/" class="event_item">Red Bluff Bull Sale</a>
            <a target="_blank" href="http://www.norcalsportshow.com/" class="event_item">Norcal Boat Sport &amp; RV Show</a>
            <a target="_blank" href="http://www.exposureshows.com/our-shows/medford.html" class="event_item">Jackson County Sportsmen's &amp; Outdoor Recreation Show</a>
    		<a target="_blank" href="http://www.sisqfair.com/" class="event_item">Yreka Sportsman Show</a>
    		<a target="_blank" href="http://www.redbluffroundup.com/" class="event_item">Red Bluff Rodeo</a>
    		<a target="_blank" href="http://www.boatnik.com/" class="event_item">Boatnik</a>
    		<a target="_blank" href="http://www.shastadistrictfair.com/" class="event_item">Shasta District Fair</a>
    		<a target="_blank" href="http://www.mtshastarunners.com/" class="event_item">Mt. Shasta 4th of July Celebration</a>
    		<a target="_blank" href="http://www.delnorte.org/event/annual-4th-of-july-event/" class="event_item">Crescent City 4th of July Celebration</a>
    		<a target="_blank" href="http://www.jcfairgrounds.com/" class="event_item">Jackson County Fair</a>
    		<a target="_blank" href="http://www.expo.deschutes.org/" class="event_item">Deschutes County Fair</a>
    		<a target="_blank" href="http://dnfairgrounds.com/" class="event_item">Del Norte County Fair</a>
    		<a target="_blank" href="http://www.co.yamhill.or.us/fair/" class="event_item">Yamhill County Fair</a>
    		<a target="_blank" href="http://www.sisqfair.com/" class="event_item">Siskiyou Golden Fair</a>
    		<a target="_blank" href="http://www.humboldtcountyfair.org/" class="event_item">Humboldt County Fair</a>
    		<a target="_blank" href="http://www.co.josephine.or.us/SectionIndex.asp?SectionID=146" class="event_item">Josephine County</a>
    		<a target="_blank" href="http://www.lakecountyfair.com/" class="event_item">Lake County Fair</a>
    		<a target="_blank" href="http://www.inter-mountainfair.com/" class="event_item">Inter Mountain Fair</a>
    		<a target="_blank" href="http://www.tbvfair.com/" class="event_item">Tulelake Butte Valley Fair</a>
    		<a target="_blank" href="http://www.mendocountyfair.com/" class="event_item">Mendocino County Fair</a>
    		<a target="_blank" href="http://www.tehamadistrictfair.com/" class="event_item">Tehama District Fair</a>
    		<a target="_blank" href="http://www.fairfun.com/fair/" class="event_item">Central Washington State Fair</a>
    		<a target="_blank" href="http://www.riverbankcheeseandwine.org/" class="event_item">River Banks Wine &amp; Cheese Festival</a>
		</div>
    </div>
</template>

<script>
export default {
    name: 'events'
}
</script>

<style lang="less">
.event_list {
    text-align: center;

    .event_item {
        display: block;
        color: #222;
        padding-bottom: 6px;
    }
}
</style>

// src/pages/events.svelte
<main class="events_page">
	<h1>Our Events</h1>

	<div class="event_list">
		<a target="_blank" href="http://www.redbluffbullsale.com/" class="event_item">Red Bluff Bull Sale</a>
		<a target="_blank" href="http://www.norcalsportshow.com/" class="event_item">Norcal Boat Sport &amp; RV Show</a>
		<a target="_blank" href="http://www.exposureshows.com/our-shows/medford.html" class="event_item">Jackson County Sportsmen's &amp; Outdoor Recreation Show</a>
		<a target="_blank" href="http://www.sisqfair.com/" class="event_item">Yreka Sportsman Show</a>
		<a target="_blank" href="http://www.redbluffroundup.com/" class="event_item">Red Bluff Rodeo</a>
		<a target="_blank" href="http://www.boatnik.com/" class="event_item">Boatnik</a>
		<a target="_blank" href="http://www.shastadistrictfair.com/" class="event_item">Shasta District Fair</a>
		<a target="_blank" href="http://www.mtshastarunners.com/" class="event_item">Mt. Shasta 4th of July Celebration</a>
		<a target="_blank" href="http://www.delnorte.org/event/annual-4th-of-july-event/" class="event_item">Crescent City 4th of July Celebration</a>
		<a target="_blank" href="http://www.jcfairgrounds.com/" class="event_item">Jackson County Fair</a>
		<a target="_blank" href="http://www.expo.deschutes.org/" class="event_item">Deschutes County Fair</a>
		<a target="_blank" href="http://dnfairgrounds.com/" class="event_item">Del Norte County Fair</a>
		<a target="_blank" href="http://www.co.yamhill.or.us/fair/" class="event_item">Yamhill County Fair</a>
		<a target="_blank" href="http://www.sisqfair.com/" class="event_item">Siskiyou Golden Fair</a>
		<a target="_blank" href="http://www.humboldtcountyfair.org/" class="event_item">Humboldt County Fair</a>
		<a target="_blank" href="http://www.co.josephine.or.us/SectionIndex.asp?SectionID=146" class="event_item">Josephine County</a>
		<a target="_blank" href="http://www.lakecountyfair.com/" class="event_item">Lake County Fair</a>
		<a target="_blank" href="http://www.inter-mountainfair.com/" class="event_item">Inter Mountain Fair</a>
		<a target="_blank" href="http://www.tbvfair.com/" class="event_item">Tulelake Butte Valley Fair</a>
		<a target="_blank" href="http://www.mendocountyfair.com/" class="event_item">Mendocino County Fair</a>
		<a target="_blank" href="http://www.tehamadistrictfair.com/" class="event_item">Tehama District Fair</a>
		<a target="_blank" href="http://www.fairfun.com/fair/" class="event_item">Central Washington State Fair</a>
		<a target="_blank" href="http://www.riverbankcheeseandwine.org/" class="event_item">River Banks Wine &amp; Cheese Festival</a>
	</div>
</main>

<style lang="less">
.event_list {
    text-align: center;

    .event_item {
        display: block;
        color: #222;
        padding-bottom: 6px;
    }
}
</style>
