// client/pages/menus.vue
<template>
    <div>
        <h1>Menus we offer</h1>

        <div class="menu_set">
            <h3>Fair Favorites</h3>
            <span>Giant Kurly Fries, Hand Dipped Corn Dogs<br />
            Taylor's Gourmet Sausages: British Bangers, Polish, Italian, and Louisiana Hots.
            Gourmet Hamburgers: Including Bacon Cheese Burgers, Western Barbeque, Mushroom Swiss, and more.
            Jumbo Hot Dogs, and Hand cut Fries.</span>
        </div>

        <div class="menu_set">
            <h3>Mix it up Frozen Drink</h3>
            <span>Fun self service drinks using a variety of popular flavors.</span>
        </div>

        <div class="menu_set">
            <h3>Funnel Cakes and Treats</h3>
            <span>Funnel Cakes, and Deep Fried Candy Bars</span>
        </div>

        <div class="menu_set">
            <h3>Mexican Food</h3>
            <span>Jumbo Burritos, Quesadillas, Tacos, Wraps, And More</span>
        </div>
    </div>
</template>

<script>
export default {
    name: 'menus',
}
</script>

<style lang="less">
.menu_set {
    margin-bottom: 20px;
}
</style>

// src/pages/menus.svelte
<main class="menu_page">
    <div class="menu_set">
        <h3>Fair Favorites</h3>
        <span>Giant Kurly Fries, Hand Dipped Corn Dogs<br />
        Taylor's Gourmet Sausages: British Bangers, Polish, Italian, and Louisiana Hots.
        Gourmet Hamburgers: Including Bacon Cheese Burgers, Western Barbeque, Mushroom Swiss, and more.
        Jumbo Hot Dogs, and Hand cut Fries.</span>
    </div>
</main>

<style lang="less">
.menu_set {
    margin-bottom: 20px;
}
</style>
