// src/pages/recommendations.svelte
<main class="recommendations_page">
	<h1>Recommendations</h1>

	<div class="recommendation">
		<h3>Cliff Munson</h3>
		<!-- <h3>January 2011</h3> -->
		<p>Southern Oregon Food &amp; Beverage (SOFAB) is one of our most treasured professional concessionaires. 2010 was my first fair as CEO here in Yreka and I can say that Daryl went out of his way to help me, both learn about fair concessions and by showing me what a true partnership is for our fair.</p>
		<p>We host a partnership get together on opening night of the fair with food and drink provided. SOFAB graciously donates most of the food for that event. Daryl and his staff are real ambassadors for our fair and we appreciate that. It is really rewarding when fair surveys mention food concessions in a positive way and the Whicheloe crew get many positive comments for their service and product.</p>
		<p>The SOFAB crew is always polite and work hard to make the fair a place where everyone can make a memory. the concession and staff are always clean and food is great, have you ever had a better curly fry? I know that Southern Oregon Food &amp; Beverage has become part of the fair experience at the Siskiyou Golden Fair and I hope the tradition continues for many years to come.</p>
		<p>I highly recommend Southern Oregon Food &amp; Beverage as a concession for any event that needs a professional concessionaire.</p>
		<p>
			I would be happy to answer any question or chat about SOFAB's dedication to our fair. Feel free to call anytime at the number listed below.
			<br><br>

			Sincerely,<br>
			Cliff Munson<br>
			CEO
			<br>

			10th District Agricultural/Siskiyou Golden Fairground<br>
			1712 Fairlane Road, Yreka CA 96097<br>
			Phone: 530-842-2767 &nbsp; Fax: 530-842-4724<br>
			Website: www.sisqfair.com &nbsp; email: info@sisqfair.com<br>
		</p>
	</div>
	<div class="divider"></div>

	<div class="recommendation">
		<h3>Alan Westhoff</h3>
		<!-- <h3>January 2011</h3> -->
		<p>I became a Fair Manager in Oregon (Josephine County-Grants Pass) in 1989 and worked with Daryl Whicheloe of Southern Oregon Food &amp; Beverage for 17 years thru 2005. I semi-retired and moved to the Portland Area and became the Manager of the Yamhill County Fair in McMinnville, Oregon.</p>
		<p>I immediately contacted Mr. Whicheloe as we needed food vendors. He has been with the Yamhill County Fair for the past 6 years and is contracted for the 2011 fair.</p>
		<p>
			SOFAB and Mr. Whicheloe are a credit to the fair industry. His operation is superb, they are honest and his presentation lends expertise to any Fair Food Midway or Food Court, or any interim event at your facility.
			<br><br>

			Sincerely,<br>
			Allan Westhoff<br>
			Fair Manager
		</p>
	</div>
	<div class="divider"></div>

	<div class="recommendation">
		<h3>Ross Rogers</h3>
		<!-- <h3>January 2011</h3> -->
		<p>Southern Oregon Food &amp; Beverage owned and operated by Daryl Whicheloe has been a staple at the Deschutes County Fair and Rodeo in Redmond, Oregon for the past 25 years. Southern Oregon Food &amp; Beverage Booth #1 is located in the heart of our Food Court where only 10 of our select food concessionaires are located. The second booth is the only food both located in front of our open class / 4H barns to accommodate those who have animals here during fair time and for the fairgoers visiting that area.</p>
		<p>At any given hour during our fair, old and young alike are in line for one of more of Daryl's tasty menu items. Because of the popularity of the Southern Oregon's they are welcome back each year. I highly recommend Daryl and his crew to accommodate any function you might be holding. I might also add that SOFAB is our highest grossing food vendor of the 30 we contract with during our week of fair.<br>
		<br>
		Sincerely,<br>
		Ross Rogers<br>
		Deschutes County Fair and Rodeo<br>
		Redmond Oregon</p>
	</div>
</main>

<style lang="less">
.divider {
    height: 2px;
    background-color: #222;
}
.recommendation {
    padding: 50px 0px;
}
</style>

// old/client/pages/recommendations.vue
<template>
    <div class="recommendations_page">
        <h1>Recommendations</h1>

        <div class="recommendation">
            <h3>Cliff Munson</h3>
        	<!-- <h3>January 2011</h3> -->
        	<p>Southern Oregon Food &amp; Beverage (SOFAB) is one of our most treasured professional concessionaires. 2010 was my first fair as CEO here in Yreka and I can say that Daryl went out of his way to help me, both learn about fair concessions and by showing me what a true partnership is for our fair.</p>
        	<p>We host a partnership get together on opening night of the fair with food and drink provided. SOFAB graciously donates most of the food for that event. Daryl and his staff are real ambassadors for our fair and we appreciate that. It is really rewarding when fair surveys mention food concessions in a positive way and the Whicheloe crew get many positive comments for their service and product.</p>
        	<p>The SOFAB crew is always polite and work hard to make the fair a place where everyone can make a memory. the concession and staff are always clean and food is great, have you ever had a better curly fry? I know that Southern Oregon Food &amp; Beverage has become part of the fair experience at the Siskiyou Golden Fair and I hope the tradition continues for many years to come.</p>
        	<p>I highly recommend Southern Oregon Food &amp; Beverage as a concession for any event that needs a professional concessionaire.</p>
        	<p>
                I would be happy to answer any question or chat about SOFAB's dedication to our fair. Feel free to call anytime at the number listed below.
                <br><br>

                Sincerely,<br>
            	Cliff Munson<br>
            	CEO
                <br>

            	10th District Agricultural/Siskiyou Golden Fairground<br>
            	1712 Fairlane Road, Yreka CA 96097<br>
            	Phone: 530-842-2767 &nbsp; Fax: 530-842-4724<br>
            	Website: www.sisqfair.com &nbsp; email: info@sisqfair.com<br>
        	</p>
        </div>
        <div class="divider"></div>

        <div class="recommendation">
            <h3>Alan Westhoff</h3>
        	<!-- <h3>January 2011</h3> -->
        	<p>I became a Fair Manager in Oregon (Josephine County-Grants Pass) in 1989 and worked with Daryl Whicheloe of Southern Oregon Food &amp; Beverage for 17 years thru 2005. I semi-retired and moved to the Portland Area and became the Manager of the Yamhill County Fair in McMinnville, Oregon.</p>
        	<p>I immediately contacted Mr. Whicheloe as we needed food vendors. He has been with the Yamhill County Fair for the past 6 years and is contracted for the 2011 fair.</p>
        	<p>
                SOFAB and Mr. Whicheloe are a credit to the fair industry. His operation is superb, they are honest and his presentation lends expertise to any Fair Food Midway or Food Court, or any interim event at your facility.
                <br><br>

            	Sincerely,<br>
            	Allan Westhoff<br>
            	Fair Manager
            </p>
        </div>
        <div class="divider"></div>

        <div class="recommendation">
            <h3>Ross Rogers</h3>
        	<!-- <h3>January 2011</h3> -->
        	<p>Southern Oregon Food &amp; Beverage owned and operated by Daryl Whicheloe has been a staple at the Deschutes County Fair and Rodeo in Redmond, Oregon for the past 25 years. Southern Oregon Food &amp; Beverage Booth #1 is located in the heart of our Food Court where only 10 of our select food concessionaires are located. The second booth is the only food both located in front of our open class / 4H barns to accommodate those who have animals here during fair time and for the fairgoers visiting that area.</p>
        	<p>At any given hour during our fair, old and young alike are in line for one of more of Daryl's tasty menu items. Because of the popularity of the Southern Oregon's they are welcome back each year. I highly recommend Daryl and his crew to accommodate any function you might be holding. I might also add that SOFAB is our highest grossing food vendor of the 30 we contract with during our week of fair.<br>
        	<br>
        	Sincerely,<br>
        	Ross Rogers<br>
        	Deschutes County Fair and Rodeo<br>
        	Redmond Oregon</p>
        </div>
    </div>
</template>

<script>
export default {
    name: 'recommendations',
}
</script>

<style lang="less">
.divider {
    height: 2px;
    background-color: #222;
}
.recommendation {
    padding: 50px 0px;
}
</style>
