// client/components/footer.vue
<template>
    <footer>
        &copy; Southern Oregon Food &amp; Beverage
    </footer>
</template>

<script>
export default {
    name: 'footer',
}
</script>

<style lang="less">
@import '../styles/mixins.less';
footer {
    .crimson();
    border-top: 2px solid #222222;
    background-color: #f7f2df;
    font-size: 24px;
    padding: 20px 0px;
    text-align: center;
}
</style>

// src/components/footer.svelte
<footer>
    <div class="contentWrapper">
        <div class="footerTitle">
            Get in Touch
        </div>
        <div class="footerText">
            Phone: (541) 941 - 9660<br>
            Email: daryl@kurlyfries.com
        </div>
    </div>
</footer>

<style lang="less">
footer {
    width: 100%;
    // height: 100px;
    // background-color: #fff;
    color: #fff;

    .footerTitle {
        font-size: 24px;
    }

    .contentWrapper {
        width: 80%;
        margin: 0px auto;
        text-align: center;
        padding: 20px 0px;
    }
}
</style>
