// client/components/menu.vue
<template>
    <menu class="menu">
        <router-link to="/" class="menu_link">Home</router-link>
        <router-link to="/photos" class="menu_link">Photos</router-link>
        <router-link to="/contact" class="menu_link">Contact</router-link>
        <router-link to="/events" class="menu_link">Events</router-link>
        <router-link to="/menus" class="menu_link">Menus</router-link>
        <router-link to="/recommendations" class="menu_link">Recommendations</router-link>
        <router-link to="/affiliates" class="menu_link">Affiliates</router-link>
    </menu>
</template>

<script>
export default {
}
</script>

<style lang="less">
@import '../styles/mixins.less';
.menu {
    text-align: center;

    .menu_link {
        .roboto();
        color: #fff;
        font-size: 24px;
        text-decoration: none;
        display: inline-block;
        padding: 10px 14px;

        @media screen and (max-width: 900px) {
            font-size: 18px;
        }

        @media screen and (max-width: 360px) {
            font-size: 14px;
        }

        &:hover {
            color: yellow;
        }
    }
}
</style>

// src/components/menu.svelte
<script>
    import {link} from 'svelte-navigator'
</script>

<nav class="menu">
    <a use:link href="/" class="menu_link">Home</a>
    <a use:link href="/gallery" class="menu_link">Gallery</a>
    <a use:link href="/contact" class="menu_link">Contact</a>
    <a use:link href="/events" class="menu_link">Events</a>
    <a use:link href="/menus" class="menu_link">Menus</a>
    <a use:link href="/recommendations" class="menu_link">Recommendations</a>
    <a use:link href="/affiliates" class="menu_link">Affiliates</a>
</nav>

<style lang="less">
.menu {
    text-align: center;
    font-family: "Open Sans";
    position: fixed;
    top: 0px;
    left: 0px;
    z-index: 150;
    width: 100%;
    height: 50px;
    background-color: rgba(0, 0, 0, 0.5);

    .menu_link {
        color: #fff;
        font-size: 24px;
        text-decoration: none;
        display: inline-block;
        padding: 10px 14px;

        @media screen and (max-width: 900px) {
            font-size: 18px;
        }

        @media screen and (max-width: 360px) {
            font-size: 14px;
        }

        &:hover {
            color: yellow;
        }
    }
}
</style>
